<ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">

    <li class="nav-item">
        <a href="http://localhost:81/proyecto/index" class="nav-link inicio">
            <i class="nav-icon fas fa-house"></i>
            <p>Inicio</p>
        </a>
    </li>

    <li class="nav-item">
        <a href="<?= PUBLIC_PATH ?>mapa" class="nav-link mapa">
            <i class="nav-icon fas fa-map-marker-alt"></i>
            <p>Mapa de centros</p>
        </a>
    </li>

    <li class="nav-item">
        <a href="<?= PUBLIC_PATH ?>campanas" class="nav-link campanas">
            <i class="nav-icon fas fa-bullhorn"></i>
            <p>Campañas especiales</p>
        </a>
    </li>

    <li class="nav-item">
        <a href="<?= PUBLIC_PATH ?>voluntariado" class="nav-link voluntariado">
            <i class="nav-icon fas fa-hands-helping"></i>
            <p>Voluntariado local</p>
        </a>
    </li>

    <li class="nav-item">
        <a href="<?= PUBLIC_PATH ?>historias_impacto" class="nav-link historias">
            <i class="nav-icon fas fa-paw"></i>
            <p>Historias de impacto</p>
        </a>
    </li>

    <li class="nav-item">
        <a href="<?= PUBLIC_PATH ?>impacto_social" class="nav-link impacto">
            <i class="nav-icon fas fa-heart"></i>
            <p>Impacto social</p>
        </a>
    </li>

    <li class="nav-item">
        <a href="<?= PUBLIC_PATH ?>donaciones" class="nav-link donaciones">
            <i class="nav-icon fas fa-hand-holding-heart"></i>
            <p>Donaciones</p>
        </a>
    </li>

    <li class="nav-item">
        <a href="<?= PUBLIC_PATH ?>donadores" class="nav-link donadores">
            <i class="nav-icon fas fa-user-friends"></i>
            <p>Donadores</p>
        </a>
    </li>

</ul>

