<div style="text-align:center;"><h1 style="font-size:3rem; font-weight:bold; text-transform:uppercase; line-height:1.1; margin:0; color:#4B2E2E;">REGISTRAR VOLUNTARIO</h1></div>

<div style="color: red; margin-bottom:20px;"><?php View::content(); ?></div>

<?= View::partial('voluntariado/_form', false, ['voluntario' => $voluntario, 'donadores'  => $donadores, 'centros'    => $centros, 'campanas'   => $campanas, 'errors'     => $errors ?? []]) ?>
</div>
