<div style="text-align:center;">
    <h1 style="font-size:3rem; font-weight:bold; text-transform:uppercase; line-height:1.1; margin:0; color:#4B2E2E;">
        REGISTRAR IMPACTO SOCIAL
    </h1>
</div>

<div style="color: red;"><?php View::content(); ?></div>

<?= View::partial('impacto_social/_form', false, ['impacto_social' => $impacto_social, 'donadores' => $donadores, 'errors' => $errors ?? []]) ?>