<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="collapse navbar-collapse" id="navbarContent">
        <div class="d-flex flex-row">
            <?= Html::link("frutas", "Frutas", ["class" => "nav-link"]) ?>&nbsp;&nbsp;&nbsp;
            <?= Html::link("clientes", "Clientes", ["class" => "nav-link"]) ?>&nbsp;&nbsp;&nbsp;
            <?= Html::link("empleados", "Empleados", ["class" => "nav-link"]) ?>&nbsp;&nbsp;&nbsp;
            <?= Html::link("ventas", "Ventas", ["class" => "nav-link"]) ?>&nbsp;&nbsp;&nbsp;
            <?= Html::link("venta_detalle", "Ventas Detalle", ["class" => "nav-link"]) ?>
        </div>
    </div>
</nav>
